ProjectFUEN-edit1/ProjectFUEN/Models/EFModels/OrderDetail.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace ProjectFUEN.Models.EFModels
{
    public partial class OrderDetail
    {
        public OrderDetail()
        {
            OrderItems = new HashSet<OrderItem>();
        }

        public int Id { get; set; }
        public int MemberId { get; set; }
        [Display(Name = "訂單日期")]
        public DateTime OrderDate { get; set; }
        [Display(Name = "地址")]
        public string Address { get; set; }
        [Display(Name = "訂單狀態")]
        public int State { get; set; }

        public virtual Member Member { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}

ProjectFUEN-edit1/ProjectFUEN/Controllers/OrderDetailsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectFUEN.Models.DTOs;
using ProjectFUEN.Models.EFModels;

using X.PagedList;

namespace ProjectFUEN.Controllers
{
    [Authorize]

    /// <summary>
    /// OrderDetail 是 orderitem, 是要查詢與顯示出貨狀態的
    /// </summary>
    public class OrderDetailsController : Controller
    {
        private readonly ProjectFUENContext _context;

        public OrderDetailsController(ProjectFUENContext context)
        {
            _context = context;
        }

        // GET: OrderDetails
        public async Task<IActionResult> Index(int? state, int? page = 1)
        {
            var projectFUENContext = _context.OrderDetails.Include(o => o.Member);
            const int pageSize = 3;

            ViewBag.OrderDetail = GetPagedProcess(page, pageSize);
            ViewBag.State = GetState(state);
            return View(await projectFUENContext.Skip<OrderDetail>(pageSize * ((page ?? 1) - 1)).Take(pageSize).ToListAsync());

        }

        protected IPagedList<OrderDetail> GetPagedProcess(int? page, int pageSize)
        {
            // 過濾從client傳送過來有問題頁數
            if (page.HasValue && page < 1)
                return null;
            // 從資料庫取得資料
            var listUnpaged = GetStuffFromDatabase();
            IPagedList<OrderDetail> pagelist = listUnpaged.ToPagedList(page ?? 1, pageSize);
            // 過濾從client傳送過來有問題頁數，包含判斷有問題的頁數邏輯
            if (pagelist.PageNumber != 1 && page.HasValue && page > pagelist.PageCount)
                return null;
            return pagelist;
        }

        protected IPagedList<OrderDetailsDTO> GetPagedProcess(int? page, int pageSize, IEnumerable<OrderDetailsDTO> listUnpaged)
        {
            // 過濾從client傳送過來有問題頁數
            if (page.HasValue && page < 1)
                return null;

            IPagedList<OrderDetailsDTO> pagelist = listUnpaged.ToPagedList(page ?? 1, pageSize);
            // 過濾從client傳送過來有問題頁數，包含判斷有問題的頁數邏輯
            if (pagelist.PageNumber != 1 && page.HasValue && page > pagelist.PageCount)
                return null;
            return pagelist;
        }


        protected IQueryable<OrderDetail> GetStuffFromDatabase()
        {
            return _context.OrderDetails;
        }

        


        [HttpGet]
        public async Task<ActionResult<IEnumerable<OrderDetailsDTO>>> Search(int state1, int? state, string account, int? page = 1)
        {
            const int pageSize = 5;
            ViewBag.State = GetState(state);

            var data = _context.OrderDetails.Include(o => o.Member).Select(x => new OrderDetailsDTO
            {
                Id = x.Id,
                Member = x.Member,
                State = x.State,
                Address = x.Address,
                OrderDate = x.OrderDate,
                EmailAccount = x.Member.EmailAccount,
            });

            if (state.HasValue) data = data.Where(x => x.State == state.Value);


            if (string.IsNullOrEmpty(account) == false)
            {
                data = data.Where(s => s.EmailAccount.Contains(account));
            }

            ViewBag.OrderDetailDto = GetPagedProcess(page, pageSize, data);



            return View(await data.Skip(pageSize * ((page ?? 1) - 1)).Take(pageSize).ToListAsync());


        }

        public IEnumerable<SelectListItem> GetState(int? State = null)
        {
            List<SelectListItem> res = new List<SelectListItem>();

            res.Add(new SelectListItem { Value = string.Empty, Text = "請選擇...", Selected = State == null });

            for (int i = 0; i < 5; i++)
            {
                res.Add(new SelectListItem { Value = i.ToString(), Text = GetStateName(i), Selected = State == i });
            }

            return res.AsEnumerable();
        }

        


        //GET: OrderDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.OrderItems == null)
            {
                return NotFound();
            }

            var SelectedorderItems = await _context.OrderItems
                .Include(o => o.OrderId)
                .FirstOrDefaultAsync(m => m.OrderId == id);

            if (SelectedorderItems == null)
            {
                return NotFound();
            }

            return View(SelectedorderItems);
        }

        


        // GET: OrderDetails/Create
        public IActionResult Create()
        {
            ViewData["MemberId"] = new SelectList(_context.Members, "Id", "EmailAccount");
            return View();
        }

        // POST: OrderDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.



        [HttpGet]
        // GET: OrderDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.OrderDetails == null)
            {
                return NotFound();
            }

            var orderDetail = await _context.OrderDetails.Include(x => x.Member).FirstAsync(x => x.Id == id);
            if (orderDetail == null)
            {
                return NotFound();
            }


            //ViewData["MemberId"] = new SelectList(_context.Members, "Id", "EmailAccount", orderDetail.MemberId);
            ViewBag.MemberId = orderDetail.Member.EmailAccount;
            ViewData["State"] = GetState(orderDetail.State);

            return View(orderDetail);
        }

        // POST: OrderDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MemberId,OrderDate,Address,State")] OrderDetail orderDetail)
        {
            string msg = "";
            if (id != orderDetail.Id)
            {
                msg = "新增失敗(更新資料列不正確)!!";
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orderDetail);
                    await _context.SaveChangesAsync();
                    msg = "新增成功 !!";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderDetailExists(orderDetail.Id))
                    {
                        msg = "新增失敗(找不到商品)!!";
                    }
                    else
                    {
                        msg = "新增失敗(其他錯誤)!!";
                    }
                }
            }

            //ViewData["MemberId"] = new SelectList(_context.Members, "Id", "EmailAccount", orderDetail.MemberId);
            // 直接重寫頁面並關閉fancybox
            await Response.WriteAsync($"<script>parent.$.fancybox.close();alert('{msg}');</script>");
            return Ok();
        }

        public async Task<ActionResult<IEnumerable<OrderItem>>> OrderitemDetails(int? id)
        {
            if (id == null || _context.OrderItems == null)
            {
                return NotFound();
            }

            var orderItem = _context.OrderItems

                .Include(o => o.Order)
                .Include(o => o.Product)
                .Where(m => m.OrderId == id)
                .AsEnumerable();
            ;
            if (orderItem == null)
            {
                return NotFound();
            }

            //var orderItem = (
            //    from a in _context.OrderItems
            //    from b in _context.OrderDetails
            //    where a.OrderId == id
            //    select new OrderItemsDTO
            //    {
            //        OrderId = a.OrderId,
            //        ProductId = a.ProductId,
            //        ProductName = a.ProductName,
            //        ProductPrice = a.ProductPrice,
            //        ProductNumber = a.ProductNumber,
            //        Order = a.Order,
            //        Product = a.Product,
            //        State = b.State,
            //    }).FirstOrDefaultAsync();

            return View(orderItem);
        }


        // GET: OrderDetails/Delete/5

        [HttpDelete]
            public void Delete(int id)
            {
                if (_context.OrderDetails == null) return;

                var orderDetail = _context.OrderDetails.Find(id);
                if (orderDetail != null)
                {
                    _context.OrderDetails.Remove(orderDetail);
                }

                _context.SaveChanges();
            }

            private bool OrderDetailExists(int id)
            {
                return _context.OrderDetails.Any(e => e.Id == id);
            }

            private string GetStateName(int state)
            {
                string StateName = "";
                switch (state)
                {
                    case 0:
                        StateName = "未出貨";
                        break;
                    case 1:
                        StateName = "已出貨";
                        break;
                    case 2:
                        StateName = "運送中";
                        break;
                    case 3:
                        StateName = "已簽收";
                        break;
                    case 4:
                        StateName = "已完成";
                        break;
                }
                return StateName;
            }
        }
    }

ProjectFUEN-edit1/ProjectFUEN/Views/OrderDetails/Details.cshtml
@model ProjectFUEN.Models.EFModels.OrderDetail

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>OrderDetail</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Member)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Member.EmailAccount)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ProjectFUEN-edit1/ProjectFUEN/Views/OrderDetails/Edit.cshtml
@model ProjectFUEN.Models.EFModels.OrderDetail

@{
    ViewData["Title"] = "Edit";
    Layout = null;
}

<head>

      <link href="~/css/styles.css" rel="stylesheet" />

</head>
<body>

   
		

    
 

		<h3 class="mt-3 text-center text-white fw-bold bg-dark">編輯訂單</h3>
 

    <hr />

    <div class="container-fluid">
    <div class="row border-1   ">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group ">
                    <label asp-for="MemberId" class="control-label">帳號:</label>
                    <label asp-for="MemberId" class="control-label">@ViewBag.MemberId</label>
                    <input type="text" asp-for="MemberId" value="@Model.MemberId" hidden readonly />
                    @*<select asp-for="MemberId" class="form-control" asp-items="ViewBag.MemberId"></select>*@

                    <span asp-validation-for="MemberId" class="text-danger"></span>
                </div>
                <div class="form-group ">
                    <label asp-for="OrderDate" class="control-label"></label>
                    <input asp-for="OrderDate" class="form-control" />
                    <span asp-validation-for="OrderDate" class="text-danger"></span>
                </div>
                <div class="form-group ">
                    <label asp-for="Address" class="control-label"></label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="form-group ">
                    <label asp-for="State" class="control-label"></label>
                    <select asp-for="State" class="form-control" asp-items="ViewBag.State"></select>
                    @*  <input asp-for="State" class="form-control" />*@
                    <span asp-validation-for="State" class="text-danger"></span>
                </div>
                <div class="form-group ">
                    <input type="submit" value="確認修改" class="btn btn-primary mt-3" />
                </div>
            </form>


        </div>
    </div>


    </div>






</body>






@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }


    <script>
        var type = $('State value')
           

     
    </script>
}

@functions {
    public string GetStateName(int state)
    {
        string StateName = "";
        switch (state)
        {
            case 0:
                StateName = "未出貨";
                break;
            case 1:
                StateName = "已出貨";
                break;
            case 2:
                StateName = "運送中";
                break;
            case 3:
                StateName = "已簽收";
                break;
            case 4:
                StateName = "已完成";
                break;
            default:
                StateName = "訂單異常";
                break;

        }
        return StateName;
    }
}

ProjectFUEN-edit1/ProjectFUEN/Views/OrderDetails/OrderItemDetails.cshtml
@model IEnumerable<ProjectFUEN.Models.EFModels.OrderItem>

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>OrderItem  <a asp-controller="OrderDetails" asp-action="Search"><i class="FunBtn fa-solid fa-circle-arrow-left text-dark"></i></a></h4>
    <hr />


    <table class="table col-10">
        <thead>
            <tr>

                <th>
                    @Html.DisplayNameFor(model => model.ProductName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProductPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProductNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Order.Address)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Product.ProductSpec)

                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Order.State)

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(model => item.ProductName)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.ProductPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.ProductNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Order.Address)
                    </td>

                    <td>
                        @Html.DisplayFor(model => item.Product.ProductSpec)

                    </td>

                    <td>
                        @GetStateName(item.Order.State)
                    </td>
                </tr>
            }
        </tbody>



    </table>













</div>
<div>
</div>

@functions {
    public string GetStateName(int state)
    {
        string StateName = "";
        switch (state)
        {
            case 0:
                StateName = "未出貨";
                break;
            case 1:
                StateName = "已出貨";
                break;
            case 2:
                StateName = "運送中";
                break;
            case 3:
                StateName = "已簽收";
                break;
            case 4:
                StateName = "已完成";
                break;
            default:
                StateName = "訂單異常";
                break;

        }
        return StateName;
    }
}

ProjectFUEN-edit1/ProjectFUEN/Views/OrderDetails/Search.cshtml
@model IEnumerable<ProjectFUEN.Models.DTOs.OrderDetailsDTO>
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@using X.PagedList.Mvc.Core.Fluent
@using X.PagedList.Web.Common

@{
    ViewData["Title"] = "訂單管理";

    var pagedList = (IPagedList)ViewBag.OrderDetailDto;
    var state = ViewBag.state as IEnumerable<SelectListItem>;
}


<div class="d-flex no-print align-items-center p-2">
    <h1>訂單管理</h1>
</div>

<div class="p-2">

    <div class="d-flex">

        @using (Html.BeginForm("Search", "OrderDetails", FormMethod.Get))
        {
            <div class="input-group">@Html.DropDownList("State", (IEnumerable<SelectListItem>)ViewBag.SelectList, new { @class = "order-state form-control" })</div>
            <div class="input-group">
                <input type="text" name="account" class="form-control" value="" id="Searchtext" placeholder="請輸入.." />
                <button type="submit" class="btn btn-dark SearchClick" value="" id="SearchClick">
                    <i class="fa-solid fa-magnifying-glass "></i>
                </button>
            </div>
        }
    </div>



    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Member.RealName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Member.EmailAccount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OrderDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.State)
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>


                    <td>
                        @Html.DisplayFor(modelItem => item.Member.RealName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Member.EmailAccount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.Raw(GetStateName(item.State))
                    </td>

                    <td>

                        <a class="FunBtn text-dark fc1" asp-action="Edit" asp-route-id="@item.Id" data-fancybox data-type="iframe">
                            <i class="fa-solid fa-pen-to-square"></i>
                        </a> |
                        @* <a asp-action="Edit" asp-route-id="@item.Id">編輯</a> |*@
                        <a class="FunBtn text-dark" asp-controller="OrderDetails" asp-action="OrderitemDetails" asp-route-id="@item.Id"><i class="fa-solid fa-circle-info"></i></a> |
                        <a class="deleteOrder FunBtn text-dark" id="@item.Id" style="cursor:pointer"><i class="fa-solid fa-trash"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div class="text-muted mx-auto ">
        <div class="align-items-center mx-auto w-50">
            @Html.PagedListPager((IPagedList)pagedList, page =>
            Url.Action("Index", new { page = page }),

            new PagedListRenderOptions {

            LiElementClasses = new string[] { "page-item" },
            PageClasses = new string[] { "page-link" },

            LinkToFirstPageFormat="<<第一頁",
            LinkToPreviousPageFormat="<",
            LinkToNextPageFormat=">",
            LinkToLastPageFormat="最末頁>>"
            })
        </div>



        第 @(pagedList.PageCount < pagedList.PageNumber ? 0 : pagedList.PageNumber) 頁，共 @pagedList.PageCount 頁。
        每頁 @pagedList.PageSize 筆資料，全部共有 @pagedList.TotalItemCount 筆資料。

    </div>
</div>

@section Scripts
    {
    <script>
        $('.fc1').fancybox({
            iframe: {
                css: {
                    width: '600px',
                    height: '500px',

                }
            },
            afterClose: function () {
                // 關閉後重load資料
                location.reload();
            }
        });



        $(".order-state").on("change", function () {
            $("#SearchClick").trigger("click");
        })


        $(".deleteOrder").on("click", function () {
            let orderid = $(this).attr("id")
            console.log(orderid)
            Swal.fire({
                title: '確定刪除?',
                icon: 'error',
                iconHtml: `<i class="fa-regular fa-trash-can"></i>`,
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: '確定',
                cancelButtonText: '取消',
                reverseButtons: true
            }).then((result) => {
                if (result.isConfirmed) {

                    $.ajax({
                        type: "Delete",
                        url: "https://localhost:7027/OrderDetails/Delete/" + orderid,
                        async: false
                    }).done(function (data) {
                        history.go(0)

                    }).fail(function (err) {
                        alert(err.statusText);
                    })



                }
            })

        })


    </script>
}
@functions {
    public string GetStateName(int state)
    {
        string StateName = "";
        switch (state)
        {
            case 0:
                StateName = @$"<span style=""color:#7B7B7B ;"">未出貨</span>";
                break;
            case 1:
                StateName = @$"<span style=""color: #006000 ;"">已出貨</span>";
                break;
            case 2:
                StateName = @$"<span style=""color: #00A600 ;"">運送中</span>";
                break;
            case 3:
                StateName = @$"<span style=""color: #02DF82 ;"">已簽收</span>";
                break;
            case 4:
                StateName = @$"<span style=""color: #00AEAE	 ;"">已完成</span>";
                break;


        }
        return StateName;
    }
}